# Generated by Django 3.2.20 on 2023-11-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
