# Generated by Django 4.1 on 2023-11-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=150)),
                ('name2', models.CharField(max_length=150)),
                ('name3', models.CharField(max_length=150)),
                ('name4', models.CharField(max_length=150)),
                ('name5', models.CharField(max_length=150)),
            ],
        ),
    ]
